# Generated by Django 3.2.9 on 2023-03-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allotments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allotment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='allotments', to='allotments.batch'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='allotments', to='allotments.branch'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='allotments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allotment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='allotments', to='allotments.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='allotment',
            unique_together={('subject', 'faculty', 'batch')},
        ),
    ]
