# Generated by Django 3.2.9 on 2023-03-04 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='allotments.program'),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('year', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='academic_years', to='allotments.batch')),
            ],
        ),
    ]
