# Generated by Django 3.2.9 on 2023-03-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotments', '0003_auto_20230304_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='id',
            field=models.BigAutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
